# Generated by Django 4.1.2 on 2022-10-28 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogitem',
            name='body',
            field=models.TextField(default=1, verbose_name='Body'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogitem',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='Title'),
            preserve_default=False,
        ),
    ]
